package com.brendon.weatherplanner;

// Class for getting weather forecast, generated by Pojo.

public class WeatherForecast {


        private Response response;

        private Forecast forecast;

        public Response getResponse() {
            return response;
        }

        public void setResponse(Response response) {
            this.response = response;
        }

        public Forecast getForecast() {
            return forecast;
        }

        public void setForecast(Forecast forecast) {
            this.forecast = forecast;
        }

        @Override
        public String toString() {
            return "ClassPojo [response = " + response + ", forecast = " + forecast + "]";
        }


     class Forecast
    {
        private Txt_forecast txt_forecast;

        private Simpleforecast simpleforecast;

        public Txt_forecast getTxt_forecast ()
        {
            return txt_forecast;
        }

        public void setTxt_forecast (Txt_forecast txt_forecast)
        {
            this.txt_forecast = txt_forecast;
        }

        public Simpleforecast getSimpleforecast ()
        {
            return simpleforecast;
        }

        public void setSimpleforecast (Simpleforecast simpleforecast)
        {
            this.simpleforecast = simpleforecast;
        }

        @Override
        public String toString()
        {
            return "ClassPojo [txt_forecast = "+txt_forecast+", simpleforecast = "+simpleforecast+"]";
        }
    }

     class Simpleforecast
    {
        private Forecastday[] forecastday;

        public Forecastday[] getForecastday ()
        {
            return forecastday;
        }

        public void setForecastday (Forecastday[] forecastday)
        {
            this.forecastday = forecastday;
        }

        @Override
        public String toString()
        {
            return "ClassPojo [forecastday = "+forecastday+"]";
        }
    }


    class Avewind
    {
        private String mph;

        private String dir;

        private String degrees;

        private String kph;

        public String getMph ()
        {
            return mph;
        }

        public void setMph (String mph)
        {
            this.mph = mph;
        }

        public String getDir ()
        {
            return dir;
        }

        public void setDir (String dir)
        {
            this.dir = dir;
        }

        public String getDegrees ()
        {
            return degrees;
        }

        public void setDegrees (String degrees)
        {
            this.degrees = degrees;
        }

        public String getKph ()
        {
            return kph;
        }

        public void setKph (String kph)
        {
            this.kph = kph;
        }

        @Override
        public String toString()
        {
            return "ClassPojo [mph = "+mph+", dir = "+dir+", degrees = "+degrees+", kph = "+kph+"]";
        }
    }


    class Snow_day
    {
        private String cm;

        private String in;

        public String getCm ()
        {
            return cm;
        }

        public void setCm (String cm)
        {
            this.cm = cm;
        }

        public String getIn ()
        {
            return in;
        }

        public void setIn (String in)
        {
            this.in = in;
        }

        @Override
        public String toString()
        {
            return "ClassPojo [cm = "+cm+", in = "+in+"]";
        }
    }


     class Snow_allday
    {
        private String cm;

        private String in;

        public String getCm ()
        {
            return cm;
        }

        public void setCm (String cm)
        {
            this.cm = cm;
        }

        public String getIn ()
        {
            return in;
        }

        public void setIn (String in)
        {
            this.in = in;
        }

        @Override
        public String toString()
        {
            return "ClassPojo [cm = "+cm+", in = "+in+"]";
        }
    }

     class Qpf_night
    {
        private String mm;

        private String in;

        public String getMm ()
        {
            return mm;
        }

        public void setMm (String mm)
        {
            this.mm = mm;
        }

        public String getIn ()
        {
            return in;
        }

        public void setIn (String in)
        {
            this.in = in;
        }

        @Override
        public String toString()
        {
            return "ClassPojo [mm = "+mm+", in = "+in+"]";
        }
    }

     class Qpf_day
    {
        private String mm;

        private String in;

        public String getMm ()
        {
            return mm;
        }

        public void setMm (String mm)
        {
            this.mm = mm;
        }

        public String getIn ()
        {
            return in;
        }

        public void setIn (String in)
        {
            this.in = in;
        }

        @Override
        public String toString()
        {
            return "ClassPojo [mm = "+mm+", in = "+in+"]";
        }
    }




     class High
    {
        private String celsius;

        private String fahrenheit;

        public String getCelsius ()
        {
            return celsius;
        }

        public void setCelsius (String celsius)
        {
            this.celsius = celsius;
        }

        public String getFahrenheit ()
        {
            return fahrenheit;
        }

        public void setFahrenheit (String fahrenheit)
        {
            this.fahrenheit = fahrenheit;
        }

        @Override
        public String toString()
        {
            return "ClassPojo [celsius = "+celsius+", fahrenheit = "+fahrenheit+"]";
        }
    }


     class Date
    {
        private String min;

        private String epoch;

        private String tz_short;

        private String monthname;

        private String weekday_short;

        private String hour;

        private String pretty;

        private String monthname_short;

        private String isdst;

        private String tz_long;

        private String ampm;

        private String weekday;

        private String yday;

        private String sec;

        private String month;

        private String year;

        private String day;

        public String getMin ()
        {
            return min;
        }

        public void setMin (String min)
        {
            this.min = min;
        }

        public String getEpoch ()
        {
            return epoch;
        }

        public void setEpoch (String epoch)
        {
            this.epoch = epoch;
        }

        public String getTz_short ()
        {
            return tz_short;
        }

        public void setTz_short (String tz_short)
        {
            this.tz_short = tz_short;
        }

        public String getMonthname ()
        {
            return monthname;
        }

        public void setMonthname (String monthname)
        {
            this.monthname = monthname;
        }

        public String getWeekday_short ()
        {
            return weekday_short;
        }

        public void setWeekday_short (String weekday_short)
        {
            this.weekday_short = weekday_short;
        }

        public String getHour ()
        {
            return hour;
        }

        public void setHour (String hour)
        {
            this.hour = hour;
        }

        public String getPretty ()
        {
            return pretty;
        }

        public void setPretty (String pretty)
        {
            this.pretty = pretty;
        }

        public String getMonthname_short ()
        {
            return monthname_short;
        }

        public void setMonthname_short (String monthname_short)
        {
            this.monthname_short = monthname_short;
        }

        public String getIsdst ()
        {
            return isdst;
        }

        public void setIsdst (String isdst)
        {
            this.isdst = isdst;
        }

        public String getTz_long ()
        {
            return tz_long;
        }

        public void setTz_long (String tz_long)
        {
            this.tz_long = tz_long;
        }

        public String getAmpm ()
        {
            return ampm;
        }

        public void setAmpm (String ampm)
        {
            this.ampm = ampm;
        }

        public String getWeekday ()
        {
            return weekday;
        }

        public void setWeekday (String weekday)
        {
            this.weekday = weekday;
        }

        public String getYday ()
        {
            return yday;
        }

        public void setYday (String yday)
        {
            this.yday = yday;
        }

        public String getSec ()
        {
            return sec;
        }

        public void setSec (String sec)
        {
            this.sec = sec;
        }

        public String getMonth ()
        {
            return month;
        }

        public void setMonth (String month)
        {
            this.month = month;
        }

        public String getYear ()
        {
            return year;
        }

        public void setYear (String year)
        {
            this.year = year;
        }

        public String getDay ()
        {
            return day;
        }

        public void setDay (String day)
        {
            this.day = day;
        }

        @Override
        public String toString()
        {
            return "ClassPojo [min = "+min+", epoch = "+epoch+", tz_short = "+tz_short+", monthname = "+monthname+", weekday_short = "+weekday_short+", hour = "+hour+", pretty = "+pretty+", monthname_short = "+monthname_short+", isdst = "+isdst+", tz_long = "+tz_long+", ampm = "+ampm+", weekday = "+weekday+", yday = "+yday+", sec = "+sec+", month = "+month+", year = "+year+", day = "+day+"]";
        }
    }


     class Snow_night
    {
        private String cm;

        private String in;

        public String getCm ()
        {
            return cm;
        }

        public void setCm (String cm)
        {
            this.cm = cm;
        }

        public String getIn ()
        {
            return in;
        }

        public void setIn (String in)
        {
            this.in = in;
        }

        @Override
        public String toString()
        {
            return "ClassPojo [cm = "+cm+", in = "+in+"]";
        }
    }


     class Low
    {
        private String celsius;

        private String fahrenheit;

        public String getCelsius ()
        {
            return celsius;
        }

        public void setCelsius (String celsius)
        {
            this.celsius = celsius;
        }

        public String getFahrenheit ()
        {
            return fahrenheit;
        }

        public void setFahrenheit (String fahrenheit)
        {
            this.fahrenheit = fahrenheit;
        }

        @Override
        public String toString()
        {
            return "ClassPojo [celsius = "+celsius+", fahrenheit = "+fahrenheit+"]";
        }
    }



     class Maxwind
    {
        private String mph;

        private String dir;

        private String degrees;

        private String kph;

        public String getMph ()
        {
            return mph;
        }

        public void setMph (String mph)
        {
            this.mph = mph;
        }

        public String getDir ()
        {
            return dir;
        }

        public void setDir (String dir)
        {
            this.dir = dir;
        }

        public String getDegrees ()
        {
            return degrees;
        }

        public void setDegrees (String degrees)
        {
            this.degrees = degrees;
        }

        public String getKph ()
        {
            return kph;
        }

        public void setKph (String kph)
        {
            this.kph = kph;
        }

        @Override
        public String toString()
        {
            return "ClassPojo [mph = "+mph+", dir = "+dir+", degrees = "+degrees+", kph = "+kph+"]";
        }
    }

     class Forecastday
    {
        private Qpf_allday qpf_allday;

        private String icon;

        private Maxwind maxwind;

        private Qpf_day qpf_day;

        private String icon_url;

        private String skyicon;

        private String pop;

        private Date date;

        private String period;

        private Snow_night snow_night;

        private String conditions;

        private Avewind avewind;

        private String avehumidity;

        private Snow_day snow_day;

        private String minhumidity;

        private High high;

        private Qpf_night qpf_night;

        private Snow_allday snow_allday;

        private Low low;

        private String maxhumidity;

        public Qpf_allday getQpf_allday ()
        {
            return qpf_allday;
        }

        public void setQpf_allday (Qpf_allday qpf_allday)
        {
            this.qpf_allday = qpf_allday;
        }

        public String getIcon ()
        {
            return icon;
        }

        public void setIcon (String icon)
        {
            this.icon = icon;
        }

        public Maxwind getMaxwind ()
        {
            return maxwind;
        }

        public void setMaxwind (Maxwind maxwind)
        {
            this.maxwind = maxwind;
        }

        public Qpf_day getQpf_day ()
        {
            return qpf_day;
        }

        public void setQpf_day (Qpf_day qpf_day)
        {
            this.qpf_day = qpf_day;
        }

        public String getIcon_url ()
        {
            return icon_url;
        }

        public void setIcon_url (String icon_url)
        {
            this.icon_url = icon_url;
        }

        public String getSkyicon ()
        {
            return skyicon;
        }

        public void setSkyicon (String skyicon)
        {
            this.skyicon = skyicon;
        }

        public String getPop ()
        {
            return pop;
        }

        public void setPop (String pop)
        {
            this.pop = pop;
        }

        public Date getDate ()
        {
            return date;
        }

        public void setDate (Date date)
        {
            this.date = date;
        }

        public String getPeriod ()
        {
            return period;
        }

        public void setPeriod (String period)
        {
            this.period = period;
        }

        public Snow_night getSnow_night ()
        {
            return snow_night;
        }

        public void setSnow_night (Snow_night snow_night)
        {
            this.snow_night = snow_night;
        }

        public String getConditions ()
        {
            return conditions;
        }

        public void setConditions (String conditions)
        {
            this.conditions = conditions;
        }

        public Avewind getAvewind ()
        {
            return avewind;
        }

        public void setAvewind (Avewind avewind)
        {
            this.avewind = avewind;
        }

        public String getAvehumidity ()
        {
            return avehumidity;
        }

        public void setAvehumidity (String avehumidity)
        {
            this.avehumidity = avehumidity;
        }

        public Snow_day getSnow_day ()
        {
            return snow_day;
        }

        public void setSnow_day (Snow_day snow_day)
        {
            this.snow_day = snow_day;
        }

        public String getMinhumidity ()
        {
            return minhumidity;
        }

        public void setMinhumidity (String minhumidity)
        {
            this.minhumidity = minhumidity;
        }

        public High getHigh ()
        {
            return high;
        }

        public void setHigh (High high)
        {
            this.high = high;
        }

        public Qpf_night getQpf_night ()
        {
            return qpf_night;
        }

        public void setQpf_night (Qpf_night qpf_night)
        {
            this.qpf_night = qpf_night;
        }

        public Snow_allday getSnow_allday ()
        {
            return snow_allday;
        }

        public void setSnow_allday (Snow_allday snow_allday)
        {
            this.snow_allday = snow_allday;
        }

        public Low getLow ()
        {
            return low;
        }

        public void setLow (Low low)
        {
            this.low = low;
        }

        public String getMaxhumidity ()
        {
            return maxhumidity;
        }

        public void setMaxhumidity (String maxhumidity)
        {
            this.maxhumidity = maxhumidity;
        }

        @Override
        public String toString()
        {
            return "ClassPojo [qpf_allday = "+qpf_allday+", icon = "+icon+", maxwind = "+maxwind+", qpf_day = "+qpf_day+", icon_url = "+icon_url+", skyicon = "+skyicon+", pop = "+pop+", date = "+date+", period = "+period+", snow_night = "+snow_night+", conditions = "+conditions+", avewind = "+avewind+", avehumidity = "+avehumidity+", snow_day = "+snow_day+", minhumidity = "+minhumidity+", high = "+high+", qpf_night = "+qpf_night+", snow_allday = "+snow_allday+", low = "+low+", maxhumidity = "+maxhumidity+"]";
        }
    }

     class Qpf_allday
    {
        private String mm;

        private String in;

        public String getMm ()
        {
            return mm;
        }

        public void setMm (String mm)
        {
            this.mm = mm;
        }

        public String getIn ()
        {
            return in;
        }

        public void setIn (String in)
        {
            this.in = in;
        }

        @Override
        public String toString()
        {
            return "ClassPojo [mm = "+mm+", in = "+in+"]";
        }
    }

     class Txt_forecast
    {
        private Forecastday[] forecastday;

        private String date;

        public Forecastday[] getForecastday ()
        {
            return forecastday;
        }

        public void setForecastday (Forecastday[] forecastday)
        {
            this.forecastday = forecastday;
        }

        public String getDate ()
        {
            return date;
        }

        public void setDate (String date)
        {
            this.date = date;
        }

        @Override
        public String toString()
        {
            return "ClassPojo [forecastday = "+forecastday+", date = "+date+"]";
        }
    }

     class Response
    {
        //private Features features;

        private String termsofService;

        private String version;

        private Error error;

        public Error getError() {
            return error;
        }

        public void setError(Error error) {
            this.error = error;
        }

        public String getTermsofService ()
        {
            return termsofService;
        }

        public void setTermsofService (String termsofService)
        {
            this.termsofService = termsofService;
        }

        public String getVersion ()
        {
            return version;
        }

        public void setVersion (String version)
        {
            this.version = version;
        }

        @Override
        public String toString()
        {
            return "ClassPojo [termsofService = "+termsofService+", version = "+version+ ", error = " + error + "]";
        }
    }

    class Features
    {
        private String forecast;

        public String getForecast ()
        {
            return forecast;
        }

        public void setForecast (String forecast)
        {
            this.forecast = forecast;
        }

        @Override
        public String toString()
        {
            return "ClassPojo [forecast = "+forecast+"]";
        }
    }


}
